<MainScreenView>:
    canvas.before:
        Color:
            rgb: app.theme_manager.bg_color
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        id: master_layout
        orientation: 'horizontal'
        padding: "15dp"
        spacing: "10dp"

        RelativeLayout:
            id: sidebar
            size_hint: (0.2,1)

        RelativeLayout:
            id: sim_grid
        
            
            

